// <auto-generated />
namespace BookStore.DataAccess.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CompleteModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CompleteModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201604080934227_CompleteModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
